### ISSUE TITLE
Installation script isn't POSIX-compliant

### ISSUE THREAD

**Issue by ketsuban** [phil-opp/nightly-libcore#5]
You advise running the installation script with `sh`, but the script contains many bashisms, thus causing it to break on any system which uses something other than `bash` to provide POSIX' `sh` (most notably Ubuntu, which uses `dash` for this purpose). The Ubuntu developers provide [a helpful rundown of commonly-used bashisms](https://wiki.ubuntu.com/DashAsBinSh) and how to emulate them POSIX-compliantly.

**Comment by phil-opp** [comment]
I'm pretty bad at shell scripts, so I'm not quite sure what's the best solution here. Would running it with bash fix the problem? (I haven't had the time to read the link yet)

**Comment by ketsuban** [comment]
That would be an adequate fix, yes, since as far as I know all distros provide the executable `bash`.

**Comment by phil-opp** [comment]
Ok, then I will update the script and the readme. Thanks for reporting!
